- alias: 'Bathroom Dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bathroom_switch
  action:
    - choose:
      # Normal ON
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.bathroom_light_state
          - service: light.turn_on
            data:
              entity_id:
                - light.bathroom
              brightness_pct: 100
      # Long press dimmed on    
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1001 }}"
        sequence:
          - service: input_boolean.turn_on
            data:
              entity_id: input_boolean.bathroom_light_state
          - service: light.turn_on
            data:
              entity_id:
                - light.bathroom
              brightness_pct: 50
      # Increase  
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2001 }}"
        sequence:
          - service: deconz.configure
            data:
              entity: light.bathroom
              field: "/action"
              data: {"bri_inc":254, "transitiontime":50}
      # Decrease
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 3001 }}"
        sequence:
          - service: deconz.configure
            data:
              entity: light.bathroom
              field: "/action"
              data: {"bri_inc":-254, "transitiontime":50}
      # Stop increase/decrease
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event in ( 2003, 3003 ) }}"
        sequence:
          - service: deconz.configure
            data:
              entity: light.bathroom
              field: "/action"
              data: {"bri_inc":0}
      # Off
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 4002 }}"
        sequence:
          - service: input_boolean.turn_off
            data:
              entity_id: input_boolean.bathroom_light_state
          - service: light.turn_off
            entity_id:
                - light.bathroom

      #default:
