- alias: 'Turn On Bed Right from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bed_right_switch
      event: 1002
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bed_diane
        brightness_pct: 30
        
- alias: 'Turn On Bedroom from Bed Right dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bed_right_switch
      event: 1001
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.bedroom
        brightness_pct: 30

- alias: 'Increase brightness Bed Right from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bed_right_switch
      event: 2001
  action:
    - service: deconz.configure
      data:
        entity: light.bedroom
        field: "/action"
        data: {"bri_inc":254, "transitiontime":50}

- alias: 'Decrease brightness Bed Right from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bed_right_switch
      event: 3001
  action:
    - service: deconz.configure
      data:
        entity: light.bedroom
        field: "/action"
        data: {"bri_inc":-254, "transitiontime":50}

- alias: 'Stop brightness Bed Right from dimmer'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: bed_right_switch
        event: 2003
    - platform: event
      event_type: deconz_event
      event_data:
        id: bed_right_switch
        event: 3003
  action:
    - service: deconz.configure
      data:
        entity: light.bedroom
        field: "/action"
        data: {"bri_inc":0}
        
          
- alias: 'Turn Off Bed Right from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bed_right_switch
      event: 4002
  action:
    - service: light.turn_off
      entity_id:
          - light.bed_diane
          - light.ceiling_1
          - light.ceiling_2
          - light.ceiling_3
          
- alias: 'Turn Off Bedroom from Bed Right dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bed_right_switch
      event: 4001
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.bedroom


