- alias: 'Bed Diane Dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: bed_right_switch
  action:
    - choose:
      # ON - Diane's side only
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id:
                - light.bed_diane
              brightness_pct: 30
      # Long ON - Bedroom on dimmed
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1001 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id:
                - light.bedroom
              brightness_pct: 30
      # Increase
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2001 }}"
        sequence:
          - service: deconz.configure
            data:
              entity: light.bedroom
              field: "/action"
              data: {"bri_inc":254, "transitiontime":50}
      # Decrease
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 3001 }}"
        sequence:
          - service: deconz.configure
            data:
              entity: light.bedroom
              field: "/action"
              data: {"bri_inc":-254, "transitiontime":50}
      # Stop increase/decrease
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event in ( 2003, 3003 ) }}"
        sequence:
          - service: deconz.configure
            data:
              entity: light.bedroom
              field: "/action"
              data: {"bri_inc":0}
      # OFF - leaving Kenneth's side on
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 4002 }}"
        sequence:
          - service: light.turn_off
            entity_id:
                - light.bed_diane
                - light.ceiling_1
                - light.ceiling_2
                - light.ceiling_3
      # Long OFF - entire bedroom
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 4001 }}"
        sequence:
          - service: light.turn_off
            data:
              entity_id:
                - light.bedroom
      #default:
