- alias: 'Bedtime Tap'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: tap_bedtime
  action:
    - choose:
      # Kenneth Sneaks To Bed
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 16 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id:
                - light.bed_kenneth
              brightness_pct: 20
      # Turn On Front Door Bedtime Tap
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 17 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id:
                - light.entrance_ceiling
                - light.terrace
              brightness_pct: 100
      # Turn Off Front Door Bedtime Tap
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 18 }}"
        sequence:
          - service: light.turn_off
            data:
              entity_id:
                - light.entrance_ceiling
                - light.terrace
      # Bedtime
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 34 }}"
        sequence:
          - service: light.turn_off
            data:
              entity_id:
                - light.kitchen
                - light.living_room
                - light.workshop
                - light.utility_room
                - light.office
                - light.hallway
                - light.entrance_ceiling



