- alias: 'Compressor Switch'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: compressor_switch
  action:
    - choose:
      # ON
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: switch.turn_on
            entity_id: switch.compressor
      # OFF
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2002 }}"
        sequence:
          - service: switch.turn_off
            entity_id: switch.compressor


- alias: 'Compressor off at 23' 
  initial_state: true
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.compressor