- alias: 'Compressor Switch On'
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: compressor_switch
      event: 1002
  action:
    - service: switch.turn_on
      entity_id: switch.compressor

- alias: 'Compressor Switch Off'
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: compressor_switch
      event: 2002
  action:
    - service: switch.turn_off
      entity_id: switch.compressor

- alias: 'Compressor off at 23' 
  initial_state: true
  trigger:
    - platform: time
      at: '23:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.compressor