- alias: 'Entire House Switch'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: entire_house
  action:
    - choose:
      # ON
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: light.turn_on
            entity_id:
              - light.entire_house
      # OFF
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2002 }}"
        sequence:
          - service: light.turn_off
            data:
              entity_id:
                - light.kitchen
                - light.living_room
                - light.workshop
                - light.utility_room
                - light.office
                - light.hallway
                - light.entrance_ceiling
                - light.closet
