- alias: 'Flush Toilet Switch'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: toilet_flusher
  action:
    - choose:
      # Long
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: switch.turn_on
            entity_id: switch.long_toilet_flush
      # Short
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2002 }}"
        sequence:
          - service: switch.turn_on
            entity_id: switch.short_toilet_flush
