# Note Terrace is a single light and not group
# so we use state instead of action for Deconz service

- alias: 'Turn On Front Door from dimmer normal'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: entrance_switch
      event: 1002
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.terrace
        brightness_pct: 100
    - service: switch.turn_on
      entity_id:
        - switch.entrance_ceiling

- alias: 'Increase brightness Front Door from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: entrance_switch
      event: 2001
  action:
    - service: deconz.configure
      data:
        entity: light.terrace
        field: "/state"
        data: {"bri_inc":254, "transitiontime":50}

- alias: 'Decrease brightness Front Door from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: entrance_switch
      event: 3001
  action:
    - service: deconz.configure
      data:
        entity: light.terrace
        field: "/state"
        data: {"bri_inc":-254, "transitiontime":50}

- alias: 'Stop brightness Front Door from dimmer'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: entrance_switch
        event: 2003
    - platform: event
      event_type: deconz_event
      event_data:
        id: entrance_switch
        event: 3003
  action:
    - service: deconz.configure
      data:
        entity: light.terrace
        field: "/state"
        data: {"bri_inc":0}
          
- alias: 'Turn Off Front Door from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: entrance_switch
      event: 4002
  action:
    - service: light.turn_off
      entity_id:
          - light.terrace
    - service: switch.turn_off
      entity_id:
        - switch.entrance_ceiling
