- alias: 'Hood Switch'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: hood
  action:
    - choose:
      # ON
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: light.turn_on
            entity_id:
              - light.hood
      # OFF
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2002 }}"
        sequence:
          - service: light.turn_off
            entity_id:
              - light.hood
