- alias: 'Kitchen Dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: kitchen_switch
  action:
    - choose:
      # Normal ON dimmed and no Vitrine
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id:
                - light.kitchen_table
                - light.microwave
                - light.sink_left
                - light.sink_right
              brightness_pct: 80
          - service: light.turn_on
            data:
              entity_id:
                - light.hood
          - service: light.turn_off
            entity_id:
              - light.vitrine
      # Long press full brightness
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1001 }}"
        sequence:
          - service: light.turn_on
            data:
              entity_id:
                - light.kitchen
              brightness_pct: 100
      # Increase
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2001 }}"
        sequence:
          - service: deconz.configure
            data:
              entity: light.kitchen
              field: "/action"
              data: {"bri_inc":254, "transitiontime":50}
      # Decrease
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 3001 }}"
        sequence:
          - service: deconz.configure
            data:
              entity: light.kitchen
              field: "/action"
              data: {"bri_inc":-254, "transitiontime":50}
      # Stop increase/decrease 
      - conditions:
          - condition: template
            value_template: > 
              {{ trigger.event.data.event == 2003 or
                 trigger.event.data.event == 3003 }}
        sequence:
          - service: deconz.configure
            data:
              entity: light.kitchen
              field: "/action"
              data: {"bri_inc":0}
      # Off
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 4002 }}"
        sequence:
          - service: light.turn_off
            data:
              entity_id:
                - light.kitchen

      #default:
      