# Office Lights

- alias: 'Office light on' 
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.office_sensor_motion
      from: 'off'
      to: 'on'
  action:
    - service: timer.cancel
      entity_id: timer.office_light
    - condition: state
      entity_id: light.computer
      state: 'off'
    - service: light.turn_on
      data:
        entity_id:
          - light.computer
          - light.makeup
        brightness_pct: 100
      
- alias: 'Office light on morning extra' 
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.office_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: '06:00:00'
      before: '09:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_panel
        brightness_pct: 60
      
- alias: 'Office light timer makeup last' 
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.office_sensor_motion
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.office_motion
      state: 'off'
  action:
    - service: timer.start
      data:
        entity_id: timer.office_light
        duration: '00:10:00'
      
- alias: 'Office light timer office last'
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.office_motion
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.office_sensor_motion
      state: 'off'
  action:
    - service: timer.start
      data:
        entity_id: timer.office_light
        duration: '00:10:00'
    
- alias: 'Office light off at timeout' 
  initial_state: true
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.office_light
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.office
        


