# light control in Living Room with Tradfri remote

- alias: 'Tradfri remote living lights on'
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_tradfri_remote
      event: 1002
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal
    - service: light.turn_on
      data:
        entity_id:
          - light.floor_lamp
        brightness: 80

- alias: 'Tradfri remote living lights off'
  initial_state: true
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_tradfri_remote
      event: 1002
  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'
  action:
    - service: light.turn_off
      entity_id:
        - light.living_room

