- alias: 'Turn On Living Room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 1002
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal
    - service: light.turn_on
      data:
        entity_id:
          - light.floor_lamp
        brightness: 100

- alias: 'Increase brightness Living Room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 2001
  action:
    - service: deconz.configure
      data:
        entity: light.living_room
        field: "/action"
        data: {"bri_inc":254, "transitiontime":50}

- alias: 'Decrease brightness Living Room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 3001
  action:
    - service: deconz.configure
      data:
        entity: light.living_room
        field: "/action"
        data: {"bri_inc":-254, "transitiontime":50}

- alias: 'Stop brightness Living Room from dimmer'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room_switch
        event: 2003
    - platform: event
      event_type: deconz_event
      event_data:
        id: living_room_switch
        event: 3003
  action:
    - service: deconz.configure
      data:
        entity: light.living_room
        field: "/action"
        data: {"bri_inc":0}
          
- alias: 'Turn Off Living Room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_switch
      event: 4002
  action:
    - service: light.turn_off
      entity_id:
          - light.living_room


