- alias: 'Living Room Curtain Switch'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: living_room_curtain_switch
  action:
    - choose:
      # Open Living Room Curtain
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: 'living-room-curtain/set'
              payload: "open"
      # Close Living Room Curtain
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2002 }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: 'living-room-curtain/set'
              payload: "close"
      # Calibrate Living Room Curtain Open
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1003 }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: 'living-room-curtain/calibrate'
              payload: "open"
      # Calibrate Living Room Curtain Closed
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2003 }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: 'living-room-curtain/calibrate'
              payload: "close"
