- alias: 'Multimedia Switch'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: multimedia_switch
  action:
    - choose:
      # Turn On TV
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "Watch TV"
      # Turn On Kodi
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1003 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "Watch KODI"
      # Turn On Chromecast
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2002 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "Watch Chromecast"
      # Turn On Squeezebox
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2003 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "Listen to Squeezebox"
      # Turn On Airport
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 3002 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "Listen to Airport"
      # Turn On Audiocast
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 3003 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "Listen to Audiocast"        
      # Turn Off Anything
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 4000 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "PowerOff"  
