# Multimedia Switch

- alias: 'Multidimmer Turn On TV'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: multimedia_switch
      event: 1002
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: "Watch TV"
        
- alias: 'Multidimmer Turn On Kodi'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: multimedia_switch
      event: 1003
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: "Watch KODI"

- alias: 'Multidimmer Turn On Chromecast'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: multimedia_switch
      event: 2002
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: "Watch Chromecast"
        
- alias: 'Multidimmer Turn On Squeezebox'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: multimedia_switch
      event: 2003
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: "Listen to Squeezebox"
        
- alias: 'Multidimmer Turn On Airport'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: multimedia_switch
      event: 3002
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: "Listen to Airport"
        
- alias: 'Multidimmer Turn On Audiocast'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: multimedia_switch
      event: 3003
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: "Listen to Audiocast"

- alias: 'Multidimmer TV Off'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: multimedia_switch
      event: 4000
  action:
    - service: remote.turn_on
      entity_id: remote.harmony_hub
      data:
        activity: "PowerOff"





