- alias: 'Turn On Office from dimmer normal'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 1002
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.computer
          - light.makeup
        brightness_pct: 100
    - service: light.turn_off
      data:
        entity_id:
          - light.office_panel

- alias: 'Turn On Office from dimmer bright'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 1001
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.computer
          - light.makeup
        brightness_pct: 100
    - service: light.turn_on
      data:
        entity_id:
          - light.office_panel
        brightness_pct: 60

- alias: 'Increase brightness Office from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 2001
  action:
    - service: deconz.configure
      data:
        entity: light.office
        field: "/action"
        data: {"bri_inc":254, "transitiontime":50}

- alias: 'Decrease brightness Office from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 3001
  action:
    - service: deconz.configure
      data:
        entity: light.office
        field: "/action"
        data: {"bri_inc":-254, "transitiontime":50}

- alias: 'Stop brightness Office from dimmer'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: office_switch
        event: 2003
    - platform: event
      event_type: deconz_event
      event_data:
        id: office_switch
        event: 3003
  action:
    - service: deconz.configure
      data:
        entity: light.office
        field: "/action"
        data: {"bri_inc":0}
          
- alias: 'Turn Off Office from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: office_switch
      event: 4002
  action:
    - service: light.turn_off
      entity_id:
          - light.office
