- alias: 'Chromecast Philips Dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: philips_remote_chromecast
  action:
    - choose:
      # Turn On Chromecast
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "Watch Chromecast"
      # Turn On TV
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1003 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "Watch TV"
      # Chromecast Volume Up Philips Remote
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2002 }}"
        sequence:
          - service: media_player.volume_up
            entity_id: media_player.chromecast_living_room       
      # Chromecast Volume Down Philips Remote
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 3002 }}"
        sequence:
          - service: media_player.volume_down
            entity_id: media_player.chromecast_living_room  
      # Turn Off Anything
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 4002 }}"
        sequence:
          - service: remote.turn_on
            entity_id: remote.harmony_hub
            data:
              activity: "PowerOff"  
