- alias: 'Open Small Window'
  initial_state: true
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: small_window_switch
        event: 1002
  action:
    - service: mqtt.publish
      data:
        topic: 'smallwindow/set'
        payload: "open"

- alias: 'Close Small Window'
  initial_state: true
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: small_window_switch
        event: 2002
  action:
    - service: mqtt.publish
      data:
        topic: 'smallwindow/set'
        payload: "close"
