- alias: 'Turn On Utility Room from dimmer normal'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: utility_switch
      event: 1002
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.utility_ceiling
        brightness_pct: 100

- alias: 'Turn On Utility Room from dimmer bright'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: utility_switch
      event: 1001
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.utility_room
        brightness_pct: 100


- alias: 'Increase brightness Utility Room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: utility_switch
      event: 2001
  action:
    - service: deconz.configure
      data:
        entity: light.utility_room
        field: "/action"
        data: {"bri_inc":254, "transitiontime":50}

- alias: 'Decrease brightness Utility Room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: utility_switch
      event: 3001
  action:
    - service: deconz.configure
      data:
        entity: light.utility_room
        field: "/action"
        data: {"bri_inc":-254, "transitiontime":50}

- alias: 'Stop brightness Utility Room from dimmer'
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: utility_switch
        event: 2003
    - platform: event
      event_type: deconz_event
      event_data:
        id: utility_switch
        event: 3003
  action:
    - service: deconz.configure
      data:
        entity: light.utility_room
        field: "/action"
        data: {"bri_inc":0}
          
- alias: 'Turn Off Utility Room from dimmer'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: utility_switch
      event: 4002
  action:
    - service: light.turn_off
      entity_id:
        - light.utility_room
