- alias: 'Workshop Blinds Switch'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: workshop_blinds_switch
  action:
    - choose:
      # Office Blinds 50
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1003 }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: 'workshop-blinds/set'
              payload: "50"
      # Office Blinds 0
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2003 }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: 'workshop-blinds/set'
              payload: "0"
      # Office Blinds Step Up
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 1002 }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: 'workshop-blinds/step'
              payload: "10"
      # Office Blinds Step Down
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.event == 2002 }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: 'workshop-blinds/step'
              payload: "-10"
